# Generated by Django 4.1.3 on 2022-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('cumpleanos', models.DateField()),
            ],
        ),
    ]
